/* SPDX-License-Identifier: Apache-2.0
 * Adapted from Stack-chan SimpleFace at 2f6b5a65e30278fdbd1c5114cab6d42cdb7b7a0d.
 * Modified for Nemossi: 240x240 projection and bounded deterministic motion.
 * Numeric values mirror tests/fixtures/stackchan-simple-face.json.
 */
#ifndef NEMOSSI_FACE_DESIGN_H
#define NEMOSSI_FACE_DESIGN_H

#define STACKCHAN_SOURCE_WIDTH 320u
#define STACKCHAN_SOURCE_HEIGHT 240u
#define STACKCHAN_TARGET_WIDTH 240u
#define STACKCHAN_TARGET_HEIGHT 240u
#define STACKCHAN_SCALE_NUMERATOR 3u
#define STACKCHAN_SCALE_DENOMINATOR 4u
#define STACKCHAN_OFFSET_X 0u
#define STACKCHAN_OFFSET_Y 30u
#define STACKCHAN_LEFT_EYE_X 90u
#define STACKCHAN_LEFT_EYE_Y 93u
#define STACKCHAN_RIGHT_EYE_X 230u
#define STACKCHAN_RIGHT_EYE_Y 96u
#define STACKCHAN_EYE_RADIUS 8u
#define STACKCHAN_EYELID_WIDTH 24u
#define STACKCHAN_EYELID_HEIGHT 24u
#define STACKCHAN_EYE_OPEN_STEPS 12u
#define STACKCHAN_MOUTH_X 160u
#define STACKCHAN_MOUTH_Y 148u
#define STACKCHAN_MOUTH_MIN_WIDTH 50u
#define STACKCHAN_MOUTH_MAX_WIDTH 90u
#define STACKCHAN_MOUTH_MIN_HEIGHT 8u
#define STACKCHAN_MOUTH_MAX_HEIGHT 58u
#define STACKCHAN_BACKGROUND_RGB 0u
#define STACKCHAN_FOREGROUND_RGB 16777215u
#define STACKCHAN_BLINK_OPEN_MIN_MS 400u
#define STACKCHAN_BLINK_OPEN_MAX_MS 5000u
#define STACKCHAN_BLINK_TRANSITION_MIN_MS 200u
#define STACKCHAN_BLINK_TRANSITION_MAX_MS 400u
#define STACKCHAN_BLINK_MIN_OPEN_MILLI 200u
#define STACKCHAN_BREATH_PERIOD_MS 6000u
#define STACKCHAN_BREATH_AMPLITUDE 6u
#define STACKCHAN_BREATH_STEPS 8u
#define STACKCHAN_MOTION_TICK_MS 33u
#define STACKCHAN_GAZE_INTERVAL_MIN_MS 300u
#define STACKCHAN_GAZE_INTERVAL_MAX_MS 2000u
#define STACKCHAN_GAZE_GAIN_MILLI 200u
#define STACKCHAN_ANIMATION_SEED 1313164623u
#define STACKCHAN_ANIMATION_SLOTS 32u

#endif
